### PR TITLE
Updated content to fit original repo

### PR DESCRIPTION
**Pull request by timnqp**
1. Updated table of content
2. Swapped Classes & SOLID
3. Updated example functions in Objects and Data Structures

### CODE REVIEW

**Comment by hienvd** [comment]
@quangphuc789 
The anchor link to 6.SOLID in table of content seems doesn't work when I click on it.
Please take a look.

**Comment by timnqp** [comment]
@hienvd @tiennv91 I have made the changes to add anchor link to 6. SOLID
I have made another pull request. Can you review?

https://github.com/hienvd/clean-code-javascript/pull/15

**Comment by hienvd** [comment]
It works now, thanks @quangphuc789 
Btw, no need to create another PR. 

@tiennv91: Looks good to me, waiting for your review :)

**Comment by timnqp** [comment]
@hienvd @tiennv91 I have made a new commit, which updated the Chinese language versions. Cheers :)

**Pull request merged**
